#!/usr/bin/env node
// Generates every derived file from the sources of truth:
//   taxonomy.json            → family and subfamily README.md files
//   transitions/**/transition.json → src/registry.ts, catalog.json,
//                              each transition's README.md, the catalog table in README.md
//
//   node scripts/build.mjs          write the files
//   node scripts/build.mjs --check  write nothing; exit 1 if any file is out of date (CI uses this)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const REPO = pkg.repository?.url?.match(/github\.com[/:](.+?)(\.git)?$/)?.[1] ?? 'GTKottman/remotion-transitions';
const MEDIA_TAG = 'media';
const mediaBase = `https://github.com/${REPO}/releases/download/${MEDIA_TAG}`;

const taxonomy = JSON.parse(fs.readFileSync(path.join(ROOT, 'taxonomy.json'), 'utf8'));
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

export const loadTransitions = () => {
  const out = [];
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name === 'transition.json') out.push({ dir: path.dirname(p), meta: JSON.parse(fs.readFileSync(p, 'utf8')) });
    }
  };
  walk(path.join(ROOT, 'transitions'));
  const famOrder = Object.fromEntries(taxonomy.families.map((f, i) => [f.slug, i]));
  const subOrder = Object.fromEntries(taxonomy.families.flatMap((f) => f.subfamilies.map((s, i) => [`${f.slug}/${s.slug}`, i])));
  return out.sort(
    (a, b) =>
      famOrder[a.meta.family] - famOrder[b.meta.family] ||
      (subOrder[`${a.meta.family}/${a.meta.subfamily}`] ?? 0) - (subOrder[`${b.meta.family}/${b.meta.subfamily}`] ?? 0) ||
      a.meta.id.localeCompare(b.meta.id),
  );
};

const media = (m) => {
  const base = `${mediaBase}/${m.id}@${m.version}`;
  return {
    preview: `${base}.mp4`,
    preview720: `${base}-720.mp4`,
    poster: `${base}.jpg`,
    ...(m.overlay ? { overlay: `${base}-overlay.mov` } : {}),
  };
};

const famBySlug = Object.fromEntries(taxonomy.families.map((f) => [f.slug, f]));
const subName = (fam, sub) => famBySlug[fam]?.subfamilies.find((s) => s.slug === sub)?.name ?? sub;
const famName = (fam) => famBySlug[fam]?.name ?? fam;

const files = new Map(); // path → content
const emit = (p, content) => files.set(path.join(ROOT, p), content);

const all = loadTransitions();
// Only folders with an index.tsx go into the registry; validate.mjs reports the rest.
const transitions = all.filter(({ dir }) => fs.existsSync(path.join(dir, 'index.tsx')));

// ---- src/registry.ts
{
  const lines = [
    '// GENERATED by scripts/build.mjs from transitions/**/transition.json. Do not edit.',
    "import type { Params, TransitionImpl, TransitionMeta } from './core';",
  ];
  transitions.forEach(({ dir }, i) => {
    const r = rel(dir);
    lines.push(`import t${i} from '../${r}';`, `import m${i} from '../${r}/transition.json';`);
  });
  lines.push(
    '',
    'export type RegistryEntry = { meta: TransitionMeta; impl: TransitionImpl<Params> };',
    '',
    'export const registry: RegistryEntry[] = [',
    ...transitions.map((_, i) => `  { meta: m${i} as unknown as TransitionMeta, impl: t${i} as unknown as TransitionImpl<Params> },`),
    '];',
    '',
  );
  emit('src/registry.ts', lines.join('\n'));
}

// ---- catalog.json (the contract read by websites; see docs/CATALOG.md)
{
  const catalog = {
    schemaVersion: 1,
    repository: `https://github.com/${REPO}`,
    mediaBase,
    families: taxonomy.families.map((f) => ({
      slug: f.slug,
      name: f.name,
      definition: f.definition,
      subfamilies: f.subfamilies.map((s) => ({ slug: s.slug, name: s.name, definition: s.definition })),
    })),
    transitions: transitions.map(({ dir, meta: m }) => ({
      id: m.id,
      name: m.name,
      version: m.version,
      summary: m.summary,
      uses: m.uses,
      family: m.family,
      subfamily: m.subfamily,
      path: rel(dir),
      facets: m.facets,
      duration: m.duration,
      overlay: m.overlay,
      requires: m.requires ?? [],
      params: m.params,
      presets: m.presets ?? [],
      authors: m.authors,
      media: media(m),
      source: `https://github.com/${REPO}/tree/main/${rel(dir)}`,
    })),
  };
  emit('catalog.json', JSON.stringify(catalog, null, 2) + '\n');
}

// ---- each transition's README.md
const importPath = (dir) => `./${rel(dir)}`;
for (const { dir, meta: m } of transitions) {
  const notesPath = path.join(dir, 'NOTES.md');
  const notes = fs.existsSync(notesPath) ? fs.readFileSync(notesPath, 'utf8').trim() : '';
  const f = m.facets;
  const md = media(m);
  const paramRows = m.params.map((p) => {
    const range = p.options ? p.options.map((o) => `\`${o}\``).join(' · ') : p.min !== undefined ? `${p.min}–${p.max}` : '';
    return `| \`${p.name}\` | ${p.type} | \`${JSON.stringify(p.default)}\` | ${range} | ${p.description} |`;
  });
  const presetRows = (m.presets ?? []).map((p) => `| \`${p.id}\` | ${p.name} | \`${JSON.stringify(p.params)}\` |`);
  const doc = [
    '<!-- GENERATED by scripts/build.mjs from transition.json (and NOTES.md). Edit those, then run npm run build. -->',
    `# ${m.name}`,
    '',
    `**${famName(m.family)} › ${subName(m.family, m.subfamily)}** · v${m.version} · ${m.duration.default} frames at 30 fps (${m.duration.min}–${m.duration.max})`,
    '',
    m.summary,
    '',
    `[Preview video](${md.preview})${md.overlay ? ` · [Alpha overlay for editing apps](${md.overlay})` : ''}`,
    '',
    '## Where it is used',
    '',
    ...m.uses.map((u) => `- ${u}`),
    '',
    '## Classification',
    '',
    '| Facet | Value |',
    '|---|---|',
    `| family | ${m.family} |`,
    `| subfamily | ${m.subfamily} |`,
    ...['structure', 'origin', 'edge', 'layers', 'space', 'timing'].map((k) => `| ${k} | ${f[k]} |`),
    `| tone | ${f.tone.join(', ')} |`,
    `| function | ${f.function.join(', ')} |`,
    `| also | ${f.also?.length ? f.also.join(', ') : '—'} |`,
    `| requires | ${m.requires?.length ? m.requires.join(', ') : '—'} |`,
    '',
    '## Use it',
    '',
    '```tsx',
    `import { linearTiming, TransitionSeries } from '@remotion/transitions';`,
    `import { toPresentation } from './src/core';`,
    `import ${camel(m.id)} from '${importPath(dir)}';`,
    '',
    '<TransitionSeries.Transition',
    `  presentation={toPresentation(${camel(m.id)}, { /* params */ })}`,
    `  timing={linearTiming({ durationInFrames: ${m.duration.default} })}`,
    '/>',
    '```',
    '',
    'Use `linearTiming`: the transition applies its own easing.' +
      (m.requires?.includes('webgl2') ? " It draws with WebGL, so render with `--gl=angle` (GPU) or `--gl=swangle` (no GPU)." : ''),
    '',
    '## Parameters',
    '',
    '| Name | Type | Default | Range | What it does |',
    '|---|---|---|---|---|',
    ...paramRows,
    '',
    ...(presetRows.length ? ['## Presets', '', '| Id | Name | Params |', '|---|---|---|', ...presetRows, ''] : []),
    ...(notes ? ['## Notes', '', notes, ''] : []),
    '## Changelog',
    '',
    ...m.changelog.map((c) => `- **${c.version}** (${c.date}): ${c.notes}`),
    '',
    `Authors: ${m.authors.join(', ')}`,
    '',
  ];
  emit(path.join(rel(dir), 'README.md'), doc.join('\n'));
}

function camel(id) {
  return id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

// ---- family and subfamily README.md files
const listFor = (fam, sub) =>
  transitions
    .filter(({ meta: m }) => m.family === fam && (!sub || m.subfamily === sub))
    .map(({ dir, meta: m }) => `| [${m.name}](${path.relative(path.join(ROOT, 'transitions', fam, sub ?? ''), dir).split(path.sep).join('/')}/) | ${sub ? '' : `${subName(fam, m.subfamily)} | `}${m.summary} |`);

for (const f of taxonomy.families) {
  const subRows = f.subfamilies.map((s) => `| [${s.name}](${s.slug}/) | ${s.definition} | ${s.examples} |`);
  const items = listFor(f.slug);
  emit(
    `transitions/${f.slug}/README.md`,
    [
      '<!-- GENERATED by scripts/build.mjs from taxonomy.json. Edit taxonomy.json (and TAXONOMY.md), then run npm run build. -->',
      `# ${f.number.toString().padStart(2, '0')} ${f.name}`,
      '',
      `Full definition: [TAXONOMY.md](../../TAXONOMY.md), section 3.`,
      '',
      `**What belongs here.** ${f.definition}`,
      '',
      `**Test.** ${f.test}`,
      '',
      `**Not here.** ${f.notHere}`,
      '',
      `**Build.** ${f.build}`,
      '',
      '## Subfamilies',
      '',
      '| Folder | What goes in it | Examples |',
      '|---|---|---|',
      ...subRows,
      '',
      '## Transitions in this family',
      '',
      ...(items.length ? ['| Transition | Subfamily | Summary |', '|---|---|---|', ...items] : ['None yet.']),
      '',
    ].join('\n'),
  );
  for (const s of f.subfamilies) {
    const its = listFor(f.slug, s.slug);
    emit(
      `transitions/${f.slug}/${s.slug}/README.md`,
      [
        '<!-- GENERATED by scripts/build.mjs from taxonomy.json. -->',
        `# ${f.name} › ${s.name}`,
        '',
        `**What belongs here.** ${s.definition}`,
        '',
        `**Examples.** ${s.examples}`,
        '',
        `**Family test.** ${f.test}`,
        '',
        'Each transition here has its own folder named by its id (lowercase, hyphens). See [CONTRIBUTING.md](../../../CONTRIBUTING.md).',
        '',
        '## Transitions',
        '',
        ...(its.length ? ['| Transition | Summary |', '|---|---|', ...its.map((r) => r.replace(/ \|  \| /, ' | '))] : ['None yet.']),
        '',
      ].join('\n'),
    );
  }
}

// ---- catalog table in README.md, between markers
{
  const readmePath = path.join(ROOT, 'README.md');
  const readme = fs.readFileSync(readmePath, 'utf8');
  const rows = transitions.map(
    ({ dir, meta: m }) =>
      `| [${m.name}](${rel(dir)}/) | ${famName(m.family)} › ${subName(m.family, m.subfamily)} | ${m.facets.structure} | ${m.facets.function.join(', ')} | ${m.overlay ? 'yes' : ''} |`,
  );
  const table = ['<!-- catalog:start -->', `${transitions.length} transitions.`, '', '| Transition | Family › Subfamily | Structure | Function | Overlay |', '|---|---|---|---|---|', ...rows, '<!-- catalog:end -->'].join('\n');
  const next = readme.replace(/<!-- catalog:start -->[\s\S]*<!-- catalog:end -->/, table);
  emit('README.md', next);
}

// ---- write or check
let stale = 0;
for (const [p, content] of files) {
  const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
  if (cur === content) continue;
  if (CHECK) {
    stale++;
    console.error(`out of date: ${rel(p)}`);
  } else {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }
}
if (CHECK && stale) {
  console.error(`\n${stale} generated file(s) are out of date. Run: npm run build`);
  process.exit(1);
}
console.log(CHECK ? 'generated files are up to date' : `built: ${transitions.length} transitions, ${files.size} files checked`);
