#!/usr/bin/env node
// Uploads rendered media to the "media" GitHub release (creating it if needed). Uses the gh CLI.
//
//   node scripts/publish-media.mjs              upload every file in media/ for each transition's
//                                               current version that the release doesn't have yet
//   node scripts/publish-media.mjs <id> ...     only these transitions
//   node scripts/publish-media.mjs --missing    print the ids whose current version has no preview
//                                               on the release (space-separated), and upload nothing
//
// Media of old versions stay on the release, so old catalog URLs keep working.

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TAG = 'media';
const args = process.argv.slice(2);
const gh = (a, opts = {}) => execFileSync('gh', a, { cwd: ROOT, encoding: 'utf8', ...opts });

const all = [];
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name === 'transition.json') all.push(JSON.parse(fs.readFileSync(p, 'utf8')));
  }
};
walk(path.join(ROOT, 'transitions'));

let existing = new Set();
try {
  existing = new Set(JSON.parse(gh(['release', 'view', TAG, '--json', 'assets'], { stdio: ['ignore', 'pipe', 'ignore'] })).assets.map((a) => a.name));
} catch {
  if (!args.includes('--missing')) {
    gh(['release', 'create', TAG, '--title', 'Media', '--latest=false', '--notes',
      'Rendered previews, posters and alpha overlays for every transition version, named <id>@<version>. Generated by CI from the code; see docs/CATALOG.md.']);
  }
}

const expected = (m) => [`${m.id}@${m.version}.mp4`, `${m.id}@${m.version}-720.mp4`, `${m.id}@${m.version}.jpg`, ...(m.overlay ? [`${m.id}@${m.version}-overlay.mov`] : [])];

if (args.includes('--missing')) {
  console.log(all.filter((m) => expected(m).some((f) => !existing.has(f))).map((m) => m.id).join(' '));
  process.exit(0);
}

const ids = args.filter((a) => !a.startsWith('--'));
const chosen = ids.length ? all.filter((m) => ids.includes(m.id)) : all;
const toUpload = [];
const missingLocal = [];
for (const m of chosen) {
  for (const f of expected(m)) {
    if (existing.has(f)) continue;
    const local = path.join(ROOT, 'media', m.id, f);
    if (fs.existsSync(local)) toUpload.push(local);
    else missingLocal.push(f);
  }
}
// Upload in small batches so one failure doesn't lose the rest.
for (let i = 0; i < toUpload.length; i += 8) {
  const batch = toUpload.slice(i, i + 8);
  gh(['release', 'upload', TAG, ...batch], { stdio: 'inherit' });
  console.log(`uploaded ${Math.min(i + 8, toUpload.length)}/${toUpload.length}`);
}
if (missingLocal.length) {
  console.error(`not rendered locally (run npm run render first):\n  ${missingLocal.join('\n  ')}`);
  process.exit(1);
}
console.log(toUpload.length ? `done: ${toUpload.length} file(s) uploaded` : 'nothing to upload: the release is up to date');
