// GENERATED by scripts/build.mjs from transitions/**/transition.json. Do not edit.
import type { Params, TransitionImpl, TransitionMeta } from './core';
import t0 from '../transitions/01-cut/match-cut/match-cut-anchor';
import m0 from '../transitions/01-cut/match-cut/match-cut-anchor/transition.json';
import t1 from '../transitions/01-cut/smash-cut/smash-cut-shake';
import m1 from '../transitions/01-cut/smash-cut/smash-cut-shake/transition.json';
import t2 from '../transitions/01-cut/smash-cut/strobe-cut';
import m2 from '../transitions/01-cut/smash-cut/strobe-cut/transition.json';
import t3 from '../transitions/01-cut/jump-cut/jump-cut-punch';
import m3 from '../transitions/01-cut/jump-cut/jump-cut-punch/transition.json';
import t4 from '../transitions/02-blend/crossfade/crossfade';
import m4 from '../transitions/02-blend/crossfade/crossfade/transition.json';
import t5 from '../transitions/02-blend/dip-to-colour/dip-to-colour';
import m5 from '../transitions/02-blend/dip-to-colour/dip-to-colour/transition.json';
import t6 from '../transitions/02-blend/luma-dissolve/luma-dissolve';
import m6 from '../transitions/02-blend/luma-dissolve/luma-dissolve/transition.json';
import t7 from '../transitions/02-blend/blend-mode/film-dissolve';
import m7 from '../transitions/02-blend/blend-mode/film-dissolve/transition.json';
import t8 from '../transitions/03-wipe/linear/linear-wipe';
import m8 from '../transitions/03-wipe/linear/linear-wipe/transition.json';
import t9 from '../transitions/03-wipe/iris/iris';
import m9 from '../transitions/03-wipe/iris/iris/transition.json';
import t10 from '../transitions/03-wipe/shape-mask/rounded-reveal';
import m10 from '../transitions/03-wipe/shape-mask/rounded-reveal/transition.json';
import t11 from '../transitions/03-wipe/shape-mask/text-mask';
import m11 from '../transitions/03-wipe/shape-mask/text-mask/transition.json';
import t12 from '../transitions/03-wipe/pattern/halftone-wipe';
import m12 from '../transitions/03-wipe/pattern/halftone-wipe/transition.json';
import t13 from '../transitions/03-wipe/pattern/stripe-wipe';
import m13 from '../transitions/03-wipe/pattern/stripe-wipe/transition.json';
import t14 from '../transitions/03-wipe/organic/noise-wipe';
import m14 from '../transitions/03-wipe/organic/noise-wipe/transition.json';
import t15 from '../transitions/04-cover/organic/ink-bleed';
import m15 from '../transitions/04-cover/organic/ink-bleed/transition.json';
import t16 from '../transitions/04-cover/organic/liquid-fill';
import m16 from '../transitions/04-cover/organic/liquid-fill/transition.json';
import t17 from '../transitions/04-cover/organic/paint-drip';
import m17 from '../transitions/04-cover/organic/paint-drip/transition.json';
import t18 from '../transitions/04-cover/geometric/shape-burst';
import m18 from '../transitions/04-cover/geometric/shape-burst/transition.json';
import t19 from '../transitions/04-cover/geometric/shape-grid';
import m19 from '../transitions/04-cover/geometric/shape-grid/transition.json';
import t20 from '../transitions/04-cover/stroke/brush-stroke';
import m20 from '../transitions/04-cover/stroke/brush-stroke/transition.json';
import t21 from '../transitions/04-cover/stroke/swoosh-lines';
import m21 from '../transitions/04-cover/stroke/swoosh-lines/transition.json';
import t22 from '../transitions/04-cover/panel/panel-slide';
import m22 from '../transitions/04-cover/panel/panel-slide/transition.json';
import t23 from '../transitions/04-cover/stinger/stinger';
import m23 from '../transitions/04-cover/stinger/stinger/transition.json';
import t24 from '../transitions/05-motion/push-slide/push';
import m24 from '../transitions/05-motion/push-slide/push/transition.json';
import t25 from '../transitions/05-motion/push-slide/slide-over';
import m25 from '../transitions/05-motion/push-slide/slide-over/transition.json';
import t26 from '../transitions/05-motion/whip/whip-pan';
import m26 from '../transitions/05-motion/whip/whip-pan/transition.json';
import t27 from '../transitions/05-motion/zoom/grid-zoom';
import m27 from '../transitions/05-motion/zoom/grid-zoom/transition.json';
import t28 from '../transitions/05-motion/zoom/zoom-through';
import m28 from '../transitions/05-motion/zoom/zoom-through/transition.json';
import t29 from '../transitions/05-motion/spin/spin';
import m29 from '../transitions/05-motion/spin/spin/transition.json';
import t30 from '../transitions/05-motion/split/shutter';
import m30 from '../transitions/05-motion/split/shutter/transition.json';
import t31 from '../transitions/05-motion/split/slice-in';
import m31 from '../transitions/05-motion/split/slice-in/transition.json';
import t32 from '../transitions/05-motion/split/split-slices';
import m32 from '../transitions/05-motion/split/split-slices/transition.json';
import t33 from '../transitions/06-distortion/glitch/rgb-glitch';
import m33 from '../transitions/06-distortion/glitch/rgb-glitch/transition.json';
import t34 from '../transitions/06-distortion/warp/liquid-warp';
import m34 from '../transitions/06-distortion/warp/liquid-warp/transition.json';
import t35 from '../transitions/06-distortion/warp/pixel-stretch';
import m35 from '../transitions/06-distortion/warp/pixel-stretch/transition.json';
import t36 from '../transitions/06-distortion/blur/defocus';
import m36 from '../transitions/06-distortion/blur/defocus/transition.json';
import t37 from '../transitions/06-distortion/pixel/pixelate';
import m37 from '../transitions/06-distortion/pixel/pixelate/transition.json';
import t38 from '../transitions/06-distortion/break/paper-tear';
import m38 from '../transitions/06-distortion/break/paper-tear/transition.json';
import t39 from '../transitions/07-morph/shape/frame-morph';
import m39 from '../transitions/07-morph/shape/frame-morph/transition.json';
import t40 from '../transitions/07-morph/type/type-morph';
import m40 from '../transitions/07-morph/type/type-morph/transition.json';
import t41 from '../transitions/07-morph/object/blob-morph';
import m41 from '../transitions/07-morph/object/blob-morph/transition.json';
import t42 from '../transitions/08-carry/object-led/dot-led';
import m42 from '../transitions/08-carry/object-led/dot-led/transition.json';
import t43 from '../transitions/08-carry/line-led/line-led';
import m43 from '../transitions/08-carry/line-led/line-led/transition.json';
import t44 from '../transitions/08-carry/type-led/type-led';
import m44 from '../transitions/08-carry/type-led/type-led/transition.json';
import t45 from '../transitions/08-carry/portal/portal-zoom';
import m45 from '../transitions/08-carry/portal/portal-zoom/transition.json';
import t46 from '../transitions/09-light/flash/flash';
import m46 from '../transitions/09-light/flash/flash/transition.json';
import t47 from '../transitions/09-light/leak/light-leak';
import m47 from '../transitions/09-light/leak/light-leak/transition.json';
import t48 from '../transitions/09-light/burn/film-burn';
import m48 from '../transitions/09-light/burn/film-burn/transition.json';
import t49 from '../transitions/09-light/flare/flare-sweep';
import m49 from '../transitions/09-light/flare/flare-sweep/transition.json';

export type RegistryEntry = { meta: TransitionMeta; impl: TransitionImpl<Params> };

export const registry: RegistryEntry[] = [
  { meta: m0 as unknown as TransitionMeta, impl: t0 as unknown as TransitionImpl<Params> },
  { meta: m1 as unknown as TransitionMeta, impl: t1 as unknown as TransitionImpl<Params> },
  { meta: m2 as unknown as TransitionMeta, impl: t2 as unknown as TransitionImpl<Params> },
  { meta: m3 as unknown as TransitionMeta, impl: t3 as unknown as TransitionImpl<Params> },
  { meta: m4 as unknown as TransitionMeta, impl: t4 as unknown as TransitionImpl<Params> },
  { meta: m5 as unknown as TransitionMeta, impl: t5 as unknown as TransitionImpl<Params> },
  { meta: m6 as unknown as TransitionMeta, impl: t6 as unknown as TransitionImpl<Params> },
  { meta: m7 as unknown as TransitionMeta, impl: t7 as unknown as TransitionImpl<Params> },
  { meta: m8 as unknown as TransitionMeta, impl: t8 as unknown as TransitionImpl<Params> },
  { meta: m9 as unknown as TransitionMeta, impl: t9 as unknown as TransitionImpl<Params> },
  { meta: m10 as unknown as TransitionMeta, impl: t10 as unknown as TransitionImpl<Params> },
  { meta: m11 as unknown as TransitionMeta, impl: t11 as unknown as TransitionImpl<Params> },
  { meta: m12 as unknown as TransitionMeta, impl: t12 as unknown as TransitionImpl<Params> },
  { meta: m13 as unknown as TransitionMeta, impl: t13 as unknown as TransitionImpl<Params> },
  { meta: m14 as unknown as TransitionMeta, impl: t14 as unknown as TransitionImpl<Params> },
  { meta: m15 as unknown as TransitionMeta, impl: t15 as unknown as TransitionImpl<Params> },
  { meta: m16 as unknown as TransitionMeta, impl: t16 as unknown as TransitionImpl<Params> },
  { meta: m17 as unknown as TransitionMeta, impl: t17 as unknown as TransitionImpl<Params> },
  { meta: m18 as unknown as TransitionMeta, impl: t18 as unknown as TransitionImpl<Params> },
  { meta: m19 as unknown as TransitionMeta, impl: t19 as unknown as TransitionImpl<Params> },
  { meta: m20 as unknown as TransitionMeta, impl: t20 as unknown as TransitionImpl<Params> },
  { meta: m21 as unknown as TransitionMeta, impl: t21 as unknown as TransitionImpl<Params> },
  { meta: m22 as unknown as TransitionMeta, impl: t22 as unknown as TransitionImpl<Params> },
  { meta: m23 as unknown as TransitionMeta, impl: t23 as unknown as TransitionImpl<Params> },
  { meta: m24 as unknown as TransitionMeta, impl: t24 as unknown as TransitionImpl<Params> },
  { meta: m25 as unknown as TransitionMeta, impl: t25 as unknown as TransitionImpl<Params> },
  { meta: m26 as unknown as TransitionMeta, impl: t26 as unknown as TransitionImpl<Params> },
  { meta: m27 as unknown as TransitionMeta, impl: t27 as unknown as TransitionImpl<Params> },
  { meta: m28 as unknown as TransitionMeta, impl: t28 as unknown as TransitionImpl<Params> },
  { meta: m29 as unknown as TransitionMeta, impl: t29 as unknown as TransitionImpl<Params> },
  { meta: m30 as unknown as TransitionMeta, impl: t30 as unknown as TransitionImpl<Params> },
  { meta: m31 as unknown as TransitionMeta, impl: t31 as unknown as TransitionImpl<Params> },
  { meta: m32 as unknown as TransitionMeta, impl: t32 as unknown as TransitionImpl<Params> },
  { meta: m33 as unknown as TransitionMeta, impl: t33 as unknown as TransitionImpl<Params> },
  { meta: m34 as unknown as TransitionMeta, impl: t34 as unknown as TransitionImpl<Params> },
  { meta: m35 as unknown as TransitionMeta, impl: t35 as unknown as TransitionImpl<Params> },
  { meta: m36 as unknown as TransitionMeta, impl: t36 as unknown as TransitionImpl<Params> },
  { meta: m37 as unknown as TransitionMeta, impl: t37 as unknown as TransitionImpl<Params> },
  { meta: m38 as unknown as TransitionMeta, impl: t38 as unknown as TransitionImpl<Params> },
  { meta: m39 as unknown as TransitionMeta, impl: t39 as unknown as TransitionImpl<Params> },
  { meta: m40 as unknown as TransitionMeta, impl: t40 as unknown as TransitionImpl<Params> },
  { meta: m41 as unknown as TransitionMeta, impl: t41 as unknown as TransitionImpl<Params> },
  { meta: m42 as unknown as TransitionMeta, impl: t42 as unknown as TransitionImpl<Params> },
  { meta: m43 as unknown as TransitionMeta, impl: t43 as unknown as TransitionImpl<Params> },
  { meta: m44 as unknown as TransitionMeta, impl: t44 as unknown as TransitionImpl<Params> },
  { meta: m45 as unknown as TransitionMeta, impl: t45 as unknown as TransitionImpl<Params> },
  { meta: m46 as unknown as TransitionMeta, impl: t46 as unknown as TransitionImpl<Params> },
  { meta: m47 as unknown as TransitionMeta, impl: t47 as unknown as TransitionImpl<Params> },
  { meta: m48 as unknown as TransitionMeta, impl: t48 as unknown as TransitionImpl<Params> },
  { meta: m49 as unknown as TransitionMeta, impl: t49 as unknown as TransitionImpl<Params> },
];
